### ISSUE TITLE
Auto-complete keyboard shortcut conflicts with default macOS Spotlight

### ISSUE THREAD

**Issue by AllenAttuned** [RecipeUI/RecipeUI#11]
The example type definition that's provided when creating a request says: 

> This will add auto-complete (CMD+SPACE) and validation!

`CMD + space` is the default hotkey for opening Spotlight search on macOS. Is there a way to remap the autocomplete shortcut?

The default example type definition:

``` typescript
// Define your request body with TypeScript.
// This will add auto-complete (CMD+SPACE) and validation!

export interface APIRequestParams {
  model: "gpt-3.5-turbo" | "gpt-4" | "gpt-3";
  messages: {
    role: "system" | "user";
    content: string;
  }[];
}
```

**Comment by JeaneC** [comment]
I butchered docs here, it should be ctrl+space. Sorry for delayed response (was travellign)
