### ISSUE TITLE
Feature request: Add support for Basic auth

### ISSUE THREAD

**Issue by thomas-alrek** [RecipeUI/RecipeUI#14]
Many API's still use Basic auth, I can work around it manually by creating the header myself, but it would be very convenient to have it built in.

**Comment by JeaneC** [comment]
This is definitely a core feature. Sorry we missed out on this and on the delay in response (had to move around a bit lately).

Please let me know if there are any APIs with Basic auth you want collections for!

**Comment by JeaneC** [comment]
@all-contributors please add @thomas-alrek for ideas
