### ISSUE TITLE
Can you report this issue to us on our discord?

### ISSUE THREAD

**Issue by bennycode** [RecipeUI/RecipeUI#17]
Hi, I just tried your software and it shows me this:

```json
{
  "error": "Something went wrong. Can you report this issue to us on our discord?"
}
```

What's your Discord channel?

## Screenshot

<img width="896" alt="image" src="https://github.com/RecipeUI/RecipeUI/assets/469989/6e694b61-58b0-4375-9fee-23c5d318b0a2">

**Comment by JeaneC** [comment]
Resolved in discord. Will add better error trackign and inspector devtool support .

**Comment by JeaneC** [comment]
@all-contributors please add @bennycode for bug
