### ISSUE TITLE
Homepage has a broken button link

### ISSUE THREAD

**Issue by Julian** [RecipeUI/RecipeUI#4]
(Hi! Nice looking project!)

The homepage seems to have a button with a broken link. Specifically:

* Go to https://home.recipeui.com/
* Click "API Network" in the navbar
* The "Check it out at RecipeUI" button doesn't lead anywhere (I guess from the button text it's meant to simply go to the RecipeUI homepage?)

**Comment by JeaneC** [comment]
Thank you @Julian  for the find
https://github.com/RecipeUI/RecipeUI/commit/ae3c372f5d269c90f444e93fece33805ec6f73f1

**Comment by JeaneC** [comment]
@all-contributors please add @Julian for bug
